# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43a54fdc7c775dfbc449e9a1090928bf0351939bae27e6e17b8079904cf1e737a037ca099a620034a3f92656018ee9da5da98c9c24271f93012d9e23ecbad239

test:
  secret_key_base: 8e3124337c45311fca6d5e00dcba930fff58f4cb3b0bc041ba30007f703aa79442d1f27bf6a5872837172ec52c2d8d446cdc35f1e892264694f52810ee01d82c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
